name: test_tools
description: Utilities used in testing Open DICOMweb packages.
version: 0.5.1
authors:
  - Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/test_tools.git

environment:
  sdk: ^1.22.0

dependencies:

dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  test: ^0.12.0
