name: test_tools
description: Utilities used in testing Open DICOMweb packages.
version: 0.5.6
authors:
  - Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/test_tools.git

environment:
  sdk: ^1.24.2

dependencies:
  common:
    path: C:/odw/sdk/common
    version: ^0.6.0
  string:
    path: C:/odw/sdk/string
    version: ^0.6.0
  system:
    path: C:/odw/sdk/system
    version: ^0.6.0
dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  test: ^0.12.0
