name: test_tools
description: Utilities used in testing Open DICOMweb packages.
version: 0.7.5
authors:
  - Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/test_tools

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  core:
    path: C:/odw/sdk/core
    version: ^0.7.6

dev_dependencies:
  benchmark_harness: any
  coverage: any
  grinder: ^0.8.0
  test:  any


