name: test_tools
description: Utilities used in testing Open DICOMweb packages.
version: 0.5.3
authors:
  - Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/test_tools.git

environment:
  sdk: ^1.21.1

dependencies:
  common:
    path: C:/odw/sdk/common
    version: ^0.5.3

dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  test: ^0.12.0
